#!/bin/bash
# Sets up my coding environment

# declare file arrays


if [ $2 = "all" ];then 

    declare -a files=("ChessMain.cpp"
		      "ChessBoard.cpp ChessBoard.h"
		      "square.cpp square.h"
		      "piece.cpp piece.h"
		      "pawn.cpp pawn.h"
		      "knight.cpp knight.h"
		      "rook.cpp rook.h"
		      "bishop.cpp bishop.h"
		      "queen.cpp queen.h"
		      "king.cpp king.h"
		      "utils.cpp utils.h")

elif [ $2 = "testSquare" ];then
    declare -a files=("TestMain.cpp"
		      "test.cpp test.h"
		      "square.cpp square.h"
		      "squareTest.cpp squareTest.h")
		      
fi    



declare -i NUM_FILES=5
NUM_FILES=${#files[@]}
NUM_FILES=$NUM_FILES+2

#set number of workspaces equal to number of files
#wmctrl -n $NUM_FILES

# loop through files by reference
for i in "${!files[@]}";do
    
    # switch to desk i
    wmctrl -s $i      
    sleep 0.1

    if [ $1 = "close" ] && [[ $i != 0 ]];then 
	#close active window
	wmctrl -c :ACTIVE:

    elif [ $1 = "open" ];then
	
	# open file in emacs
	emacs ${files[$i]} & disown
	sleep 0.5

	if [ $i == 0 ];then
	    xdotool key super+Right # snap right
	    sleep 0.1
	else
	    #maximize window
	    wmctrl -r :ACTIVE: -b add,maximized_vert,maximized_horz
	fi
	    
	sleep 0.5
	
    fi
    
done

# return to desktop 0
wmctrl -s 0

#	    xdotool key alt+Tab

