#!/bin/bash
# Sets up my coding environment

# declare file arrays

if  [ $2 = "all" ];then
    declare -a files=("ChessMain.cpp"
		      "ChessBoard.cpp ChessBoard.h"
		      "square.cpp square.h"
		      "piece.cpp piece.h"
		      "pawn.cpp pawn.h"
		      "knight.cpp knight.h"
		      #"rook.cpp rook.h"
		      #"bishop.cpp bishop.h"
		      #"queen.cpp queen.h"
		      "king.cpp king.h"
		      "utils.cpp utils.h")

elif [ $2 = "test" ];then
    declare -a files=("TestMain.cpp"
		      "ChessBoard.cpp ChessBoard.h"
		      "ChessBoardTest.cpp ChessBoardTest.h"
		      "square.cpp square.h"
		      "squareTest.cpp squareTest.h"
		      "piece.cpp piece.h"
		      "pieceTest.cpp pieceTest.h"
		      "pawn.cpp pawn.h"	      
		      "knight.cpp knight.h"
		      "king.cpp king.h"
		      "otherPiecesTest.cpp otherPiecesTest.h"
		      "utils.cpp utils.h"
		      "utilsTest.cpp utilsTest.h")		      
fi
    
# get current workspace
declare -i INITIAL_WORKSPACE;
INITIAL_WORKSPACE=$(wmctrl -d | grep '*' | cut -d ' ' -f1)

declare -i CURRENT_WORKSPACE=$INITIAL_WORKSPACE

# loop through files by reference
for i in "${!files[@]}";do
    
    # switch to desk i
    wmctrl -s $CURRENT_WORKSPACE

    # increment current workspace
    CURRENT_WORKSPACE=$CURRENT_WORKSPACE+1
 
    sleep 0.1

    if [ $1 = "close" ] && [[ $i != 0 ]];then 
	#close active window
	wmctrl -c :ACTIVE:

    elif [ $1 = "open" ];then
	
	# open file in emacs
	emacs ${files[$i]} & disown
	sleep 0.5

	if [ $i == 0 ];then
	    xdotool key super+Right # snap right
	    sleep 0.1
	else
	    #maximize window
	    wmctrl -r :ACTIVE: -b add,maximized_vert,maximized_horz
	fi
	    
	sleep 0.5
	
    fi
    
    
done

# return to initial workspace
wmctrl -s $INITIAL_WORKSPACE

#	    xdotool key alt+Tab

